
Define ObjectType {
                    DataBaseObject	
                    QueryObject
					}
DataBaseObject	JavaClass { DataBase.DataBaseObject               } Palette { 'database' } DefaultDisplayModel 	{ Circle 				}

QueryObject	JavaClass { DataBase.QueryObject               } Palette { 'database' } DefaultDisplayModel 	{ Circle 				}
Define DataBaseObject { InventoryDataBase }

Define QueryObject{ InventoryQueryObject }
