
Define ObjectType {
                    DataObject
                    QueryObject
					}
DataObject	JavaClass { DataBase.DataObject               } Palette { 'database' } DefaultDisplayModel 	{ Circle 				}

QueryObject	JavaClass { DataBase.QueryObject               } Palette { 'database' } DefaultDisplayModel 	{ Circle 				}

Define DataObject { InventoryDataBase }
Define QueryObject{ InventoryQueryObject }
