Define			DisplayModel			{ Pixels }
Pixels			Shape					{ PIXELS }
Define			DisplayModel			{ Rectangle }
Rectangle		Shape					{ RECTANGLE }
Define				DisplayModel		{ Circle }
Circle				Shape				{ CIRCLE }
Define				DisplayModel		{ Arrow2D }
Arrow2D				Shape				{ ARROW2D }
Define				DisplayModel		{ Triangle }
Triangle			Shape				{ TRIANGLE }

Define				DisplayModel		{ BarGauge2D }
BarGauge2D			Shape				{ BARGAUGE2D }

Define				ColladaModel		{ CrossHairs }
CrossHairs			ColladaFile			{ '<res>/shapes/CrossHairs.dae' }

Define		ColladaModel	{ Cube }
Cube		ColladaFile		{ '<res>/shapes/cube.dae' }
DisplayEntity	DefaultDisplayModel { Cube }

Define		ColladaModel	{ Sphere }
Sphere		ColladaFile		{ '<res>/shapes/Sphere.dae' }


Define ColladaModel { Truck3D }
Truck3D ColladaFile { '<res>/AROMA_resources/Shapes/Sin t_tulo.dae' }

Define ColladaModel { BuildingYellow }
BuildingYellow ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding.dae' }

Define ColladaModel { SawmillFacility }
SawmillFacility ColladaFile { '<res>/AROMA_resources/Shapes/SawmillFacility.dae' }

Define ColladaModel { BioenergyFacility }
BioenergyFacility ColladaFile { '<res>/AROMA_resources/Shapes/BioenergyFacility.dae' }

Define ColladaModel { OSBFacility }
OSBFacility ColladaFile { '<res>/AROMA_resources/Shapes/OSBFacility.dae' }

Define ColladaModel { PulpmillFacility }
PulpmillFacility ColladaFile { '<res>/AROMA_resources/Shapes/PulpmillFacility.dae' }
Define ColladaModel { PelletFacility }
PelletFacility ColladaFile { '<res>/AROMA_resources/Shapes/PelletFacility.dae' }


Define ColladaModel { PlywoodFacility }
PlywoodFacility ColladaFile { '<res>/AROMA_resources/Shapes/PlywoodFacility.dae' }

Define ColladaModel { SawmillFacilitySimple }
SawmillFacilitySimple ColladaFile { '<res>/AROMA_resources/Shapes/SawmillFacility-simple.dae' }

Define ColladaModel { BioenergyFacilitySimple }
BioenergyFacilitySimple ColladaFile { '<res>/AROMA_resources/Shapes/BioenergyFacility-simple.dae' }

Define ColladaModel { OSBFacilitySimple }
OSBFacilitySimple ColladaFile { '<res>/AROMA_resources/Shapes/OSBFacility-simple.dae' }

Define ColladaModel { PulpmillFacilitySimple }
PulpmillFacilitySimple ColladaFile { '<res>/AROMA_resources/Shapes/PulpmillFacility-simple.dae' }
Define ColladaModel { PelletFacilitySimple }
PelletFacilitySimple ColladaFile { '<res>/AROMA_resources/Shapes/PelletFacility-simple.dae' }


Define ColladaModel { PlywoodFacilitySimple }
PlywoodFacilitySimple ColladaFile { '<res>/AROMA_resources/Shapes/PlywoodFacility-simple.dae' }

Define ColladaModel { BuildingPurple }
BuildingPurple ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding_Purple.dae' }

Define ColladaModel { BuildingBlue }
BuildingBlue ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding_Blue.dae' }

Define ColladaModel { BuildingPink }
BuildingPink ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding_Pink.dae' }

Define ColladaModel { BuildingRed }
BuildingRed ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding_Red.dae' }

Define ColladaModel { BuildingGreen }
BuildingGreen ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding_Green.dae' }

Define ColladaModel { BuildingWhite }
BuildingWhite ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding_White.dae' }

Define ColladaModel { BuildingSkyBlue }
BuildingSkyBlue ColladaFile { '<res>/AROMA_resources/Shapes/FactoryBuliding_SkyBlue.dae' }

Define ColladaModel { FactoryPink }
FactoryPink ColladaFile { '<res>/AROMA_resources/Shapes/FactoryPink.dae' }

Define ColladaModel { Cargo3D }
Cargo3D ColladaFile { '<res>/AROMA_resources/Shapes/WoodchipTrailer.dae' }

Define ColladaModel { CargoContent3D }
CargoContent3D ColladaFile { '<res>/AROMA_resources/Shapes/CargoContent.dae' }

Define ColladaModel { StockpileContent1 }
StockpileContent1 ColladaFile { '<res>/AROMA_resources/Shapes/Woodpile.dae' }

Define ColladaModel { StockpileContent2 }
StockpileContent2 ColladaFile { '<res>/AROMA_resources/Shapes/WoodChipPile2.dae' }

Define ColladaModel { LoaderBodyModel }
LoaderBodyModel ColladaFile { '<res>/AROMA_resources/Shapes/LoaderBody.dae' }

Define ColladaModel { LoaderBaseModel }
LoaderBaseModel ColladaFile { '<res>/AROMA_resources/Shapes/LoaderBase.dae' }

Define ColladaModel { WoodChipperModel }
WoodChipperModel ColladaFile { '<res>/AROMA_resources/Shapes/AutoSave_cone.dae' }

Define ImageModel { SawmillIcon }
SawmillIcon ImageFile { '<res>/AROMA_resources/Shapes/Saw-2D.png' }

Define ImageModel { PulpmillIcon }
PulpmillIcon ImageFile { '<res>/AROMA_resources/Shapes/Pulp-2D.png' }

Define ImageModel { BioenergyIcon }
BioenergyIcon ImageFile { '<res>/AROMA_resources/Shapes/Bioenergy-2D.png' }

Define ImageModel { OSBIcon }
OSBIcon ImageFile { '<res>/AROMA_resources/Shapes/OSB-2D.png' }

Define ImageModel { PelletIcon }
PelletIcon ImageFile { '<res>/AROMA_resources/Shapes/Pellet-2D.png' }

Define ImageModel { PlyIcon }
PlyIcon ImageFile { '<res>/AROMA_resources/Shapes/Plywood-2D.png' }
