
Define ObjectType {
                    GraphicSimulation
                    EntityTracer 
                    "                   ScriptEntity
                  }

GraphicSimulation       JavaClass { com.sandwell.JavaSimulation.Simulation     } Palette { 'Simulation Controls' } DragAndDrop { FALSE }
Define GraphicSimulation { Simulation }
EntityTracer            JavaClass { com.jaamsim.basicsim.EntityTracer          } Palette { 'Simulation Controls' } DragAndDrop { FALSE }
"ScriptEntity            JavaClass { com.sandwell.JavaSimulation3D.ScriptEntity   } Palette { 'Simulation Controls' } DragAndDrop { FALSE }

